services:
  mysql_service:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imobiliaria

    ports:
      - "3307:3306"
    networks:
      - gabriel_network
  spring-boot-app:
    container_name: springbootapp
    build: .
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - mysql_service
    networks:a
      - gabriel_network

networks:
  gabriel_network:
    driver: bridge